https://school.programmers.co.kr/learn/courses/30/lessons/144856
--GROUP BY 연습하기 
--접근방법
-- 1월판매목록인 북리스트 출력하기
-- 저자별, 카테고리 별 매출 출력하기
-- 저자 ID 가 같은 저자 테이블이랑 조인후 정리해서 출력하기


SELECT C.AUTHOR_ID,D.AUTHOR_NAME,C.CATEGORY, C.TOTAL_SALES
FROM (SELECT  A.CATEGORY,A.AUTHOR_ID, SUM((A.PRICE*B.SALES))AS TOTAL_SALES
FROM BOOK AS A JOIN BOOK_SALES AS B ON A.BOOK_ID = B.BOOK_ID
 WHERE YEAR(SALES_DATE)='2022' AND MONTH(SALES_DATE)='01'
 GROUP BY A.AUTHOR_ID, A.CATEGORY)AS C JOIN AUTHOR AS D ON C.AUTHOR_ID = D.AUTHOR_ID 
ORDER BY C.AUTHOR_ID,C.CATEGORY DESC; 