-- 날짜 형식 
--DATE_FORMAT(컬럼명,형식)
--%Y(1996),%M(SEP),%D(19th),%y(96),%m(09),%d(19)

--null관련 
--특정 컬럼이 null이면 생략해라
--AND NOT 컬럼명 IS NULL**  이렇게 하면 됨

--UNION ALL 
--두 테이블을 합치는거면 조인 아니구 합집합!! 데이터 겹치는거 안없앨거면 UNION ALL 사용 
--컬럼 개수가 맞아야하는데 없는 경우에 NULL 해줘하면 그냥 SELECT 에 NULL AS 컬럼명 해준다.

--조금 복잡했던 것만 가지고 왔음.. 

SELECT A.REST_ID,A.REST_NAME,A.FOOD_TYPE,A.FAVORITES,A.ADDRESS,ROUND(AVG(B.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS A INNER JOIN REST_REVIEW AS B ON A.REST_ID = B.REST_ID
GROUP BY REST_ID
HAVING ADDRESS LIKE ('서울%')
ORDER BY SCORE DESC,FAVORITES DESC;

SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d") as SALES_DATE ,PRODUCT_ID,USER_ID,SALES_AMOUNT
from ONLINE_SALE 
WHERE DATE_FORMAT(SALES_DATE,"%m")='03'
union all 
select DATE_FORMAT(SALES_DATE,"%Y-%m-%d") as SALES_DATE ,PRODUCT_ID,NULL as USER_ID,SALES_AMOUNT
from OFFLINE_SALE 
WHERE DATE_FORMAT(SALES_DATE,"%m")='03'
order by SALES_DATE,PRODUCT_ID,USER_ID;