-- USED_GOODS_BOARD와 USED_GOODS_USER 테이블에서 
-- 완료된 중고 거래의 총금액이 70만 원 이상인 사람의 회원 ID, 닉네임, 총거래금액을 조회하는 SQL문을 작성해주세요. 
-- 결과는 총거래금액을 기준으로 오름차순 정렬해주세요.

-- https://school.programmers.co.kr/learn/courses/30/lessons/164668

--완료된 중고거래 총금액이 70만원인사람 조회하기 
SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD
WHERE STATUS ='DONE'
GROUP BY WRITER_ID
HAVING TOTAL_SALES>=700000

-- 회원테이블과 조인해서 아이디 닉네임 총금액 합치기
SELECT B.USER_ID, B.NICKNAME,A.TOTAL_SALES
FROM (SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD
WHERE STATUS ='DONE'
GROUP BY WRITER_ID
HAVING TOTAL_SALES>=700000)AS A JOIN USED_GOODS_USER AS B ON A.WRITER_ID = B.USER_ID;

-- 총금액 오름차순으로 정렬
SELECT B.USER_ID, B.NICKNAME,A.TOTAL_SALES
FROM (SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD
WHERE STATUS ='DONE'
GROUP BY WRITER_ID
HAVING TOTAL_SALES>=700000)AS A JOIN USED_GOODS_USER AS B ON A.WRITER_ID = B.USER_ID
ORDER BY TOTAL_SALES;