
-- 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중 
-- 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고 
-- 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차에 대해서 자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE) 리스트를 출력
-- 결과는 대여 금액을 기준으로 내림차순 정렬하고, 
-- 대여 금액이 같은 경우 자동차 종류를 기준으로 오름차순 정렬, 
-- 자동차 종류까지 같은 경우 자동차 ID를 기준으로 내림차순 정렬해주세요.

-- https://school.programmers.co.kr/learn/courses/30/lessons/157339


-- 대여 범위가 11월 1일부터 11월 30일까지에 들어가는 차번호 구하기(해당날짜에 대여하지 못하는)
SELECT DISTINCT CAR_ID  
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(END_DATE,'%Y-%m-%d')>'2022-11-01' AND DATE_FORMAT(START_DATE,'%Y-%m-%d')<'2022-11-30';

-- CAR_RENTAL_COMPANY_CAR 테이블에서 제외시켜주기, 그리고 차 타입 세단 suv인걸로 추리기
SELECT CAR_ID, CAR_TYPE, DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE IN ('세단','SUV') AND 
CAR_ID NOT IN 
(SELECT DISTINCT CAR_ID  
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(END_DATE,'%Y-%m-%d')>'2022-11-01' AND DATE_FORMAT(START_DATE,'%Y-%m-%d')<'2022-11-30');

-- 30일동안의 대여 할인 비율 구하기 
SELECT CAR_TYPE, DISCOUNT_RATE 
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE CAR_TYPE IN ('세단','SUV') AND DURATION_TYPE ='30일 이상';

-- 계산한 금액이 50만원 이상 200만원 미만인 리스트 구하기, 정렬조건 넣어주면 끝! 
SELECT A.CAR_ID, A.CAR_TYPE, ROUND((A.DAILY_FEE*((100-B.DISCOUNT_RATE)/100)*30),0)AS TOTAL
FROM (SELECT CAR_ID, CAR_TYPE, DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE IN ('세단','SUV')AND CAR_ID NOT IN (
SELECT DISTINCT CAR_ID  
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(END_DATE,'%Y-%m-%d')>'2022-11-01' AND DATE_FORMAT(START_DATE,'%Y-%m-%d')<'2022-11-30')
)AS A JOIN (SELECT CAR_TYPE, DISCOUNT_RATE 
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE CAR_TYPE IN ('세단','SUV') AND DURATION_TYPE ='30일 이상') AS B ON A.CAR_TYPE = B.CAR_TYPE
WHERE ROUND((A.DAILY_FEE*((100-B.DISCOUNT_RATE)/100)*30),0) BETWEEN 500000 AND 2000000
ORDER BY TOTAL DESC, A.CAR_TYPE,A.CAR_ID;

